export const ingredients = [
  { key: 'milk', value: 'milk', text: 'Milk' },
  { key: 'butter', value: 'butter', text: 'Butter' },
  { key: 'yogurt', value: 'yogurt', text: 'Yogurt' },
  { key: 'parmesan', value: 'parmesan', text: 'Parmesan' },
  { key: 'cheddar', value: 'cheddar', text: 'Cheddar' },
  { key: 'mozzarella', value: 'mozzarella', text: 'Mozzarella' },
  { key: 'cream', value: 'cream', text: 'Cream' },
  { key: 'goat milk', value: 'goat milk', text: 'Goat Milk' },
  { key: 'almond milk', value: 'almond milk', text: 'Almond Milk' },
  { key: 'feta', value: 'feta', text: 'Feta' },
  { key: 'brie', value: 'brie', text: 'Brie' },
  { key: 'onion', value: 'onion', text: 'Onion' },
  { key: 'tomato', value: 'tomato', text: 'Tomato' },
  { key: 'lettuce', value: 'lettuce', text: 'Lettuce' },
  { key: 'garlic', value: 'garlic', text: 'Garlic' },
  { key: 'potato', value: 'potato', text: 'Potato' },
  { key: 'carrot', value: 'carrot', text: 'Carrot' },
  { key: 'bell pepper', value: 'bell pepper', text: 'Bell Pepper' },
  { key: 'basil', value: 'basil', text: 'Basil' },
  { key: 'broccoli', value: 'broccoli', text: 'Broccoli' },
  { key: 'corn', value: 'corn', text: 'Corn' },
  { key: 'spinach', value: 'spinach', text: 'Spinach' },
  { key: 'mushroom', value: 'mushroom', text: 'Mushroom' },
  { key: 'green beans', value: 'green beans', text: 'Green Beans' },
  { key: 'cucumber', value: 'cucumber', text: 'Cucumber' },
  { key: 'ginger', value: 'ginger', text: 'Ginger' },
  { key: 'salad greens', value: 'salad greens', text: 'Salad Greens' },
  { key: 'sweet potato', value: 'sweet potato', text: 'sweet potato' },
  { key: 'celery', value: 'celery', text: 'Celery' },
  { key: 'cabbage', value: 'cabbage', text: 'Cabbage' },
  { key: 'cauliflower', value: 'cauliflower', text: 'Cauliflower' },
  { key: 'green onion', value: 'green onion', text: 'Green Onion' },
  { key: 'asparagus', value: 'asparagus', text: 'Asparagus' },
  { key: 'chili pepper', value: 'chili pepper', text: 'Chili Pepper' },
  { key: 'lemon', value: 'lemon', text: 'Lemon' },
  { key: 'apple', value: 'apple', text: 'Apple' },
  { key: 'banana', value: 'banana', text: 'Banana' },
  { key: 'lime', value: 'lime', text: 'Lime' },
  { key: 'strawberry', value: 'strawberry', text: 'Strawberry' },
  { key: 'orange', value: 'orange', text: 'Orange' },
  { key: 'grapes', value: 'grapes', text: 'Grapes' },
  { key: 'avocado', value: 'avocado', text: 'Avocado' },
  { key: 'peach', value: 'peach', text: 'Peach' },
  { key: 'blueberry', value: 'blueberry', text: 'Blueberry' },
  { key: 'pineapple', value: 'pineapple', text: 'Pineapple' },
  { key: 'cantaloupe', value: 'cantaloupe', text: 'Cantaloupe' },
  { key: 'cherries', value: 'cherries', text: 'Cherries' },
  { key: 'pear', value: 'pear', text: 'Pear' },
  { key: 'mango', value: 'mango', text: 'Mango' },
  { key: 'raspberry', value: 'raspberry', text: 'Raspberry' },
  { key: 'blackberry', value: 'blackberry', text: 'Blackberry' },
  { key: 'raisin', value: 'raisin', text: 'Raisin' },
  { key: 'plum', value: 'plum', text: 'Plum' },
  { key: 'nectarine', value: 'nectarine', text: 'Nectarine' },
  { key: 'rice', value: 'rice', text: 'Rice' },
  { key: 'pasta', value: 'pasta', text: 'Pasta' },
  { key: 'flour', value: 'flour', text: 'Flour' },
  { key: 'bread', value: 'bread', text: 'Bread' },
  { key: 'baking powder', value: 'baking powder', text: 'baking powder' },
  { key: 'baking soda', value: 'baking soda', text: 'baking soda' },
  { key: 'bread crumbs', value: 'bread crumbs', text: 'Bread Crumbs' },
  { key: 'rolled oats', value: 'rolled oats', text: 'Rolled Oats' },
  { key: 'noodle', value: 'noodle', text: 'Noodle' },
  { key: 'tortilla', value: 'tortilla', text: 'Tortilla' },
  { key: 'brown rice', value: 'brown rice', text: 'Brown Rice' },
  { key: 'quinoa', value: 'quinoa', text: 'Quinoa' },
  { key: 'cornstarch', value: 'cornstarch', text: 'Cornstarch' },
  { key: 'sugar', value: 'sugar', text: 'Sugar' },
  { key: 'honey', value: 'honey', text: 'Honey' },
  { key: 'cinnamon', value: 'cinnamon', text: 'Cinnamon' },
  { key: 'vanilla', value: 'vanilla', text: 'Vanilla' },
  { key: 'garlic powder', value: 'garlic powder', text: 'Garlic Powder' },
  { key: 'paprika', value: 'paprika', text: 'Paprika' },
  { key: 'oregano', value: 'oregano', text: 'Oregano' },
  { key: 'allspice', value: 'allspice', text: 'Allspice' },
  { key: 'bay leaves', value: 'bay leaves', text: 'Bay Leaves' },
  { key: 'cayenne', value: 'cayenne', text: 'Cayenne' },
  { key: 'chili powder', value: 'chili powder', text: 'Chili Powder' },
  { key: 'clove', value: 'clove', text: 'Clove' },
  { key: 'cumin', value: 'cumin', text: 'Cumin' },
  { key: 'curry powder', value: 'curry powder', text: 'Curry Powder' },
  { key: 'onion powder', value: 'onion powder', text: 'Onion Powder' },
  { key: 'rosemary', value: 'rosemary', text: 'Rosemary' },
  { key: 'dill weed', value: 'dill weed', text: 'Dill Weed' },
  { key: 'nutmeg', value: 'nutmeg', text: 'Nutmeg' },
  { key: 'saffron', value: 'saffron', text: 'Saffron' },
  { key: 'sage', value: 'sage', text: 'Sage' },
  { key: 'tarragon', value: 'tarragon', text: 'Tarragon' },
  { key: 'thyme', value: 'thyme', text: 'Thyme' },
  { key: 'chicken breast', value: 'chicken breast', text: 'Chicken Breast' },
  { key: 'ground beef', value: 'ground beef', text: 'Ground Beef' },
  { key: 'bacon', value: 'bacon', text: 'Bacon' },
  { key: 'sausage', value: 'sausage', text: 'sausage' },
  { key: 'steak', value: 'steak', text: 'steak' },
  { key: 'pork chop', value: 'pork chop', text: 'Pork Chop' },
  { key: 'chicken thigh', value: 'chicken thigh', text: 'Chicken Thigh' },
  { key: 'turkey', value: 'turkey', text: 'Turkey' },
  { key: 'pork', value: 'pork', text: 'Pork' },
  { key: 'ham', value: 'ham', text: 'Ham' },
  { key: 'salami', value: 'salami', text: 'Salami' },
  { key: 'chicken', value: 'chicken', text: 'chicken' },
  { key: 'pork roast', value: 'pork roast', text: 'Pork Roast' },
  { key: 'chicken wing', value: 'chicken wing', text: 'Chicken Wing' },
  { key: 'shrimp', value: 'shrimp', text: 'Shrimp' },
  { key: 'tuna', value: 'tuna', text: 'Tuna' },
  { key: 'salmon', value: 'salmon', text: 'Salmon' },
  { key: 'tilapia', value: 'tilapia', text: 'Tilapia' },
  { key: 'catfish', value: 'catfish', text: 'Catfish' },
  { key: 'crab', value: 'crab', text: 'Crab' },
  { key: 'cod', value: 'cod', text: 'Cod' },  
  { key: 'clam', value: 'clam', text: 'Clam' },
  { key: 'lobster', value: 'lobster', text: 'Lobster' },
  { key: 'mayonnaise', value: 'mayonnaise', text: 'Mayonnaise' },
  { key: 'ketchup', value: 'ketchup', text: 'Ketchup' },
  { key: 'mustard', value: 'mustard', text: 'mustard' },
  { key: 'vinegar', value: 'vinegar', text: 'Vinegar' },
  { key: 'soy sauce', value: 'soy sauce', text: 'Soy Sauce' },
  { key: 'balsamic vinegar', value: 'balsamic vinegar', text: 'Balsamic Vinegar' },
  { key: 'olive oil', value: 'olive oil', text: 'Olive Oil' },
  { key: 'vegetable oil', value: 'vegetable oil', text: 'Vegetable Oil' },
  { key: 'canola oil', value: 'canola oil', text: 'Canola Oil' },
  { key: 'sesame oil', value: 'sesame oil', text: 'Sesame Oil' },
  { key: 'coconut oil', value: 'coconut oil', text: 'Coconut Oil' },
  { key: 'peanut oil', value: 'peanut oil', text: 'Peanut Oil' },
  { key: 'sunflower oil', value: 'sunflower oil', text: 'Sunflower Oil' },
  { key: 'tofu', value: 'tofu', text: 'Tofu' },
  { key: 'peas', value: 'peas', text: 'Peas' },
  { key: 'black bean', value: 'black bean', text: 'Black Bean' },
  { key: 'lentil', value: 'lentil', text: 'Lentil' },
  { key: 'chickpea', value: 'chickpea', text: 'Chickpea' },
  { key: 'refried beans', value: 'refried beans', text: 'Refried Beans' },
  { key: 'chili beans', value: 'chili beans', text: 'Chili Beans' },
  { key: 'lima bean', value: 'lima bean', text: 'Lima Bean' },
  { key: 'kidney bean', value: 'kidney bean', text: 'Kidney Bean' },
  { key: 'peanut', value: 'peanut', text: 'Peanut' },
  { key: 'almond', value: 'almond', text: 'Almond' },
  { key: 'walnut', value: 'walnut', text: 'Walnut' },
  { key: 'pecan', value: 'pecan', text: 'Pecan' },
  { key: 'cashew', value: 'cashew', text: 'Cashew' },
  { key: 'peanut butter', value: 'peanut butter', text: 'Peanut Butter' },
  { key: 'margarine', value: 'margarine', text: 'Margarine' },
  { key: 'coconut milk', value: 'coconut milk', text: 'Coconut Milk' },
  { key: 'soy milk', value: 'soy milk', text: 'Soy Milk' },
];
